import type { NewsCityData } from "./types";

/**
 * Mock content for MC News City. Shape mirrors what a future news /
 * economic-calendar / AI-summary integration would return, so swapping this
 * for a live fetch later is a data-layer change only.
 */
export const NEWS_CITY_DATA: NewsCityData = {
  overview: {
    riskLevel: "moderate",
    mainDriver: "Fed rate-path repricing after sticky core CPI",
    latestEvent: "Core CPI printed 3.1% YoY, above the 2.9% consensus",
    sentiment: "risk-on",
    volatility: "Medium",
  },
  centralBanks: [
    {
      id: "fed",
      name: "Federal Reserve",
      shortName: "Fed",
      headline: "Fed holds rates, signals one cut still on the table for Q4",
      rate: "4.25% - 4.50%",
      rateExpectation: "1 cut priced in by December",
      direction: "hawkish",
      liquidity: "Restrictive",
      impacts: [
        { label: "NASDAQ", direction: "down" },
        { label: "USD", direction: "up" },
      ],
      impact: "Pressures NQ/ES higher-for-longer discount rate; growth names most sensitive.",
      lastUpdated: "2h ago",
    },
    {
      id: "ecb",
      name: "European Central Bank",
      shortName: "ECB",
      headline: "ECB trims deposit rate 25bps, cites cooling euro-area inflation",
      rate: "2.75%",
      rateExpectation: "Gradual easing path into 2027",
      direction: "dovish",
      liquidity: "Easing",
      impacts: [
        { label: "EUR", direction: "down" },
        { label: "DAX", direction: "up" },
      ],
      impact: "Weaker EUR supports USD strength; modest tailwind for US dollar-denominated futures.",
      lastUpdated: "5h ago",
    },
    {
      id: "boj",
      name: "Bank of Japan",
      shortName: "BoJ",
      headline: "BoJ keeps policy rate unchanged, watching yen weakness closely",
      rate: "0.50%",
      rateExpectation: "Next hike unlikely before Q1",
      direction: "neutral",
      liquidity: "Accommodative",
      impacts: [
        { label: "USD/JPY", direction: "up" },
        { label: "Equity vol", direction: "up" },
      ],
      impact: "Carry-trade unwind risk remains a tail risk for equity volatility.",
      lastUpdated: "1d ago",
    },
  ],
  commodities: [
    {
      id: "oil",
      name: "Crude Oil (WTI)",
      price: "$74.20",
      change: "+1.8%",
      direction: "rising",
      supplyRisk: "medium",
      geopoliticalImpact: "OPEC+ supply discipline holding; Middle East shipping risk keeping a floor under price.",
      headline: "OPEC+ reaffirms output quotas, oil extends weekly gain",
    },
    {
      id: "gold",
      name: "Gold",
      price: "$2,614",
      change: "+0.6%",
      direction: "rising",
      supplyRisk: "low",
      geopoliticalImpact: "Central bank buying and safe-haven demand offsetting real-yield headwinds.",
      headline: "Gold grinds higher as central banks keep stacking reserves",
    },
  ],
  macroForces: [
    {
      id: "inflation",
      name: "Inflation",
      headline: "Core CPI 3.1%, hotter than expected on shelter and services",
      metric: "3.1%",
      metricLabel: "Core CPI YoY",
      direction: "rising",
      level: "HIGH",
      intensity: 0.85,
      impact: "Keeps pressure on the Fed to stay patient; headwind for rate-sensitive growth names.",
    },
    {
      id: "employment",
      name: "Employment",
      headline: "Payrolls add 142k, unemployment steady at 4.1%",
      metric: "4.1%",
      metricLabel: "Unemployment rate",
      direction: "flat",
      level: "MODERATE",
      intensity: 0.55,
      impact: "Labor market cooling gradually, not breaking — supports a soft-landing narrative.",
    },
    {
      id: "growth",
      name: "Growth",
      headline: "Q3 GDP revised up to 2.8% on resilient consumer spending",
      metric: "2.8%",
      metricLabel: "GDP growth (QoQ ann.)",
      direction: "rising",
      level: "POSITIVE",
      intensity: 0.7,
      impact: "Solid growth backdrop supports earnings, but complicates the case for near-term cuts.",
    },
  ],
  marketHQ: {
    sentiment: "risk-on",
    regime: "Risk-On",
    drivers: ["AI capex optimism", "Earnings strength", "Lower long-end yields"],
    indices: [
      { id: "nq", name: "Nasdaq 100 Futures", ticker: "NQ", price: "22,450.25", change: "+0.74%", direction: "rising" },
      { id: "es", name: "S&P 500 Futures", ticker: "ES", price: "6,812.50", change: "+0.41%", direction: "rising" },
    ],
  },
  news: [
    {
      id: "n1",
      time: "8m ago",
      minutesAgo: 8,
      source: "Fed Wire",
      category: "central-bank",
      impact: "high",
      direction: "down",
      title: "Fed holds rates, Powell keeps one Q4 cut on the table",
      summary: "FOMC leaves the target range at 4.25–4.50% and reiterates a data-dependent, higher-for-longer stance. Growth names most rate-sensitive.",
      tickers: ["NQ", "USD"],
      link: { kind: "bank", id: "fed" },
    },
    {
      id: "n2",
      time: "22m ago",
      minutesAgo: 22,
      source: "BLS",
      category: "macro",
      impact: "high",
      direction: "up",
      title: "Core CPI 3.1% YoY, hotter than the 2.9% consensus",
      summary: "Shelter and services keep inflation sticky, pressuring the Fed to stay patient. Headwind for rate-sensitive equities.",
      tickers: ["CPI", "ES"],
      link: { kind: "macro", id: "inflation" },
    },
    {
      id: "n3",
      time: "41m ago",
      minutesAgo: 41,
      source: "Reuters",
      category: "commodity",
      impact: "medium",
      direction: "up",
      title: "OPEC+ reaffirms output quotas, WTI extends weekly gain",
      summary: "Supply discipline plus Middle East shipping risk keep a floor under crude. Watch second-round inflation effects.",
      tickers: ["CL", "WTI"],
      link: { kind: "commodity", id: "oil" },
    },
    {
      id: "n4",
      time: "1h ago",
      minutesAgo: 63,
      source: "ECB Press",
      category: "central-bank",
      impact: "medium",
      direction: "down",
      title: "ECB trims deposit rate 25bps as euro-area inflation cools",
      summary: "Gradual easing path signalled into 2027. Weaker EUR supports USD strength and dollar-denominated futures.",
      tickers: ["EUR", "DAX"],
      link: { kind: "bank", id: "ecb" },
    },
    {
      id: "n5",
      time: "2h ago",
      minutesAgo: 120,
      source: "Bloomberg",
      category: "markets",
      impact: "high",
      direction: "up",
      title: "Nasdaq futures grind higher on AI capex optimism",
      summary: "Risk-on regime holds as earnings strength and lower long-end yields underpin megacap tech. NQ 22,450, ES 6,812.",
      tickers: ["NQ", "ES"],
      link: { kind: "hq" },
    },
    {
      id: "n6",
      time: "3h ago",
      minutesAgo: 168,
      source: "WGC",
      category: "commodity",
      impact: "low",
      direction: "up",
      title: "Gold grinds higher as central banks keep stacking reserves",
      summary: "Safe-haven demand and official-sector buying offset real-yield headwinds. Gold at $2,614.",
      tickers: ["GC", "XAU"],
      link: { kind: "commodity", id: "gold" },
    },
    {
      id: "n7",
      time: "4h ago",
      minutesAgo: 240,
      source: "BLS",
      category: "macro",
      impact: "medium",
      direction: "neutral",
      title: "Payrolls add 142k, unemployment steady at 4.1%",
      summary: "Labour market cooling gradually, not breaking — consistent with a soft-landing narrative.",
      tickers: ["NFP"],
      link: { kind: "macro", id: "employment" },
    },
    {
      id: "n8",
      time: "6h ago",
      minutesAgo: 360,
      source: "BEA",
      category: "macro",
      impact: "medium",
      direction: "up",
      title: "Q3 GDP revised up to 2.8% on resilient consumer spending",
      summary: "Solid growth backdrop supports earnings but complicates the case for near-term cuts.",
      tickers: ["GDP"],
      link: { kind: "macro", id: "growth" },
    },
    {
      id: "n9",
      time: "9h ago",
      minutesAgo: 540,
      source: "Nikkei",
      category: "central-bank",
      impact: "low",
      direction: "neutral",
      title: "BoJ holds policy, watching yen weakness closely",
      summary: "Next hike unlikely before Q1. Carry-trade unwind remains a tail risk for equity volatility.",
      tickers: ["JPY", "USDJPY"],
      link: { kind: "bank", id: "boj" },
    },
    {
      id: "n10",
      time: "11h ago",
      minutesAgo: 660,
      source: "AP",
      category: "geopolitics",
      impact: "medium",
      direction: "up",
      title: "Red Sea shipping disruption lifts freight and energy risk premia",
      summary: "Rerouting around the Cape lengthens supply chains, feeding into commodity and inflation risk.",
      tickers: ["CL", "CPI"],
      link: { kind: "commodity", id: "oil" },
    },
  ],
};
