import type { NewsCityData } from "./types";

/**
 * Mock content for the Market Intelligence Hub. Shape mirrors what a future
 * news / economic-calendar / AI-summary integration would return, so swapping
 * this for a live fetch later is a data-layer change only.
 */
export const NEWS_CITY_DATA: NewsCityData = {
  overview: {
    riskLevel: "moderate",
    mainDriver: "Fed rate-path repricing after sticky core CPI",
    latestEvent: "Core CPI printed 3.1% YoY, above the 2.9% consensus",
    sentiment: "risk-on",
    volatility: "Medium",
  },
  centralBanks: [
    {
      id: "fed",
      name: "Federal Reserve",
      shortName: "Fed",
      headline: "Fed holds rates, signals one cut still on the table for Q4",
      rate: "4.25% - 4.50%",
      rateExpectation: "1 cut priced in by December",
      direction: "hawkish",
      liquidity: "Restrictive",
      impacts: [
        { label: "NASDAQ", direction: "down" },
        { label: "USD", direction: "up" },
      ],
      impact: "Pressures NQ/ES higher-for-longer discount rate; growth names most sensitive.",
      lastUpdated: "2h ago",
    },
    {
      id: "ecb",
      name: "European Central Bank",
      shortName: "ECB",
      headline: "ECB trims deposit rate 25bps, cites cooling euro-area inflation",
      rate: "2.75%",
      rateExpectation: "Gradual easing path into 2027",
      direction: "dovish",
      liquidity: "Easing",
      impacts: [
        { label: "EUR", direction: "down" },
        { label: "DAX", direction: "up" },
      ],
      impact: "Weaker EUR supports USD strength; modest tailwind for US dollar-denominated futures.",
      lastUpdated: "5h ago",
    },
    {
      id: "boj",
      name: "Bank of Japan",
      shortName: "BoJ",
      headline: "BoJ keeps policy rate unchanged, watching yen weakness closely",
      rate: "0.50%",
      rateExpectation: "Next hike unlikely before Q1",
      direction: "neutral",
      liquidity: "Accommodative",
      impacts: [
        { label: "USD/JPY", direction: "up" },
        { label: "Equity vol", direction: "up" },
      ],
      impact: "Carry-trade unwind risk remains a tail risk for equity volatility.",
      lastUpdated: "1d ago",
    },
  ],
  commodities: [
    {
      id: "oil",
      name: "Crude Oil (WTI)",
      price: "$74.20",
      change: "+1.8%",
      direction: "rising",
      supplyRisk: "medium",
      geopoliticalImpact: "OPEC+ supply discipline holding; Middle East shipping risk keeping a floor under price.",
      headline: "OPEC+ reaffirms output quotas, oil extends weekly gain",
    },
    {
      id: "gold",
      name: "Gold",
      price: "$2,614",
      change: "+0.6%",
      direction: "rising",
      supplyRisk: "low",
      geopoliticalImpact: "Central bank buying and safe-haven demand offsetting real-yield headwinds.",
      headline: "Gold grinds higher as central banks keep stacking reserves",
    },
  ],
  macroForces: [
    {
      id: "inflation",
      name: "Inflation",
      headline: "Core CPI 3.1%, hotter than expected on shelter and services",
      metric: "3.1%",
      metricLabel: "Core CPI YoY",
      direction: "rising",
      level: "HIGH",
      intensity: 0.85,
      impact: "Keeps pressure on the Fed to stay patient; headwind for rate-sensitive growth names.",
    },
    {
      id: "employment",
      name: "Employment",
      headline: "Payrolls add 142k, unemployment steady at 4.1%",
      metric: "4.1%",
      metricLabel: "Unemployment rate",
      direction: "flat",
      level: "MODERATE",
      intensity: 0.55,
      impact: "Labor market cooling gradually, not breaking — supports a soft-landing narrative.",
    },
    {
      id: "growth",
      name: "Growth",
      headline: "Q3 GDP revised up to 2.8% on resilient consumer spending",
      metric: "2.8%",
      metricLabel: "GDP growth (QoQ ann.)",
      direction: "rising",
      level: "POSITIVE",
      intensity: 0.7,
      impact: "Solid growth backdrop supports earnings, but complicates the case for near-term cuts.",
    },
  ],
  earnings: [
    {
      id: "nvda",
      ticker: "NVDA",
      company: "NVIDIA",
      headline: "NVIDIA beats on data-center demand, guides above consensus",
      surprise: "+12% EPS beat",
      direction: "rising",
      impact: "Semiconductors ↑ · lifts the broader AI-capex trade",
    },
    {
      id: "msft",
      ticker: "MSFT",
      company: "Microsoft",
      headline: "Microsoft cloud growth cools slightly, still ahead of estimates",
      surprise: "+3% EPS beat",
      direction: "flat",
      impact: "Mega-cap tech ↑ · Azure capex commentary in focus",
    },
  ],
  marketHQ: {
    sentiment: "risk-on",
    regime: "Risk-On",
    drivers: ["AI capex optimism", "Earnings strength", "Lower long-end yields"],
    indices: [
      { id: "nq", name: "Nasdaq 100 Futures", ticker: "NQ", price: "22,450.25", change: "+0.74%", direction: "rising" },
      { id: "es", name: "S&P 500 Futures", ticker: "ES", price: "6,812.50", change: "+0.41%", direction: "rising" },
    ],
  },
  news: [
    {
      id: "n1",
      tag: "alert",
      time: "8m ago",
      minutesAgo: 8,
      source: "Fed Wire",
      category: "central-bank",
      impact: "high",
      direction: "down",
      title: "Fed: Rate expectations shifted",
      marketImpact: "NASDAQ ↓",
      confidence: 87,
      whatHappened:
        "FOMC leaves the target range at 4.25–4.50% and Powell reiterates a data-dependent, higher-for-longer stance, pushing back on an early-2026 cut.",
      whyItMatters:
        "Rate-path repricing raises the discount rate applied to long-duration growth cash flows — the most rate-sensitive corner of the Nasdaq.",
      historicalContext:
        "Similar hawkish holds in the last two cycles (Sep '23, Jun '24) each preceded a 2-4% NQ pullback within five sessions before stabilizing.",
      affectedAssets: ["NASDAQ", "S&P 500", "USD", "Bonds"],
      tickers: ["NQ", "USD"],
    },
    {
      id: "n2",
      tag: "alert",
      time: "22m ago",
      minutesAgo: 22,
      source: "BLS",
      category: "macro",
      impact: "very-high",
      direction: "up",
      title: "CPI release: core inflation surprises hot",
      marketImpact: "Volatility increase",
      confidence: 91,
      whatHappened: "Core CPI printed 3.1% YoY versus a 2.9% consensus, driven by shelter and services components staying sticky.",
      whyItMatters:
        "A hotter print narrows the Fed's room to cut, and is the single biggest driver of today's repricing across rates and equities.",
      historicalContext:
        "The last three upside CPI surprises each triggered an intraday NQ swing of 1.5%+ within the first 30 minutes of the print.",
      affectedAssets: ["Rates", "USD", "S&P 500", "Gold"],
      tickers: ["CPI", "ES"],
    },
    {
      id: "n3",
      tag: "event",
      time: "41m ago",
      minutesAgo: 41,
      source: "Reuters",
      category: "commodity",
      impact: "medium",
      direction: "up",
      title: "Oil supply event: OPEC+ reaffirms quotas",
      marketImpact: "Energy ↑",
      confidence: 74,
      whatHappened: "OPEC+ reaffirms current output quotas; Middle East shipping risk keeps a floor under Brent and WTI.",
      whyItMatters: "Sustained supply discipline plus freight risk feeds into headline inflation, a second-round risk for rate expectations.",
      historicalContext: "Prior OPEC+ quota reaffirmations have tended to add 1-2% to WTI over the following week absent a demand shock.",
      affectedAssets: ["Energy", "Inflation"],
      tickers: ["CL", "WTI"],
    },
    {
      id: "n4",
      tag: "event",
      time: "1h ago",
      minutesAgo: 63,
      source: "ECB Press",
      category: "central-bank",
      impact: "medium",
      direction: "down",
      title: "ECB trims deposit rate 25bps",
      marketImpact: "EUR ↓",
      confidence: 82,
      whatHappened: "ECB cuts the deposit rate 25bps as euro-area inflation continues cooling, signalling a gradual easing path into 2027.",
      whyItMatters: "A weaker EUR supports USD strength, a modest tailwind for dollar-denominated futures like NQ and ES.",
      historicalContext: "The last two ECB cuts each coincided with a 0.5-1% DXY move over the following 48 hours.",
      affectedAssets: ["EUR", "DAX", "USD"],
      tickers: ["EUR", "DAX"],
    },
    {
      id: "n5",
      tag: "event",
      time: "1h ago",
      minutesAgo: 74,
      source: "Bloomberg",
      category: "earnings",
      impact: "high",
      direction: "up",
      title: "NVIDIA earnings surprise",
      marketImpact: "Semiconductors ↑",
      confidence: 92,
      whatHappened: "NVIDIA beat on data-center demand and guided above consensus for the coming quarter.",
      whyItMatters: "As the AI-capex bellwether, an NVDA beat tends to lift the whole semiconductor complex and reinforces the Nasdaq's growth narrative.",
      historicalContext: "NVDA's last four earnings beats each added an average of 0.6% to NQ the following session.",
      affectedAssets: ["Semiconductors", "NASDAQ"],
      tickers: ["NVDA", "NQ"],
    },
    {
      id: "n6",
      tag: "event",
      time: "2h ago",
      minutesAgo: 120,
      source: "Desk Wire",
      category: "markets",
      impact: "medium",
      direction: "up",
      title: "Nasdaq futures grind higher on AI capex optimism",
      marketImpact: "NQ +0.74% · ES +0.41%",
      confidence: 68,
      whatHappened: "Risk-on regime holds as earnings strength and lower long-end yields underpin megacap tech.",
      whyItMatters: "Confirms the broader risk appetite backdrop that most other signals today are playing against.",
      historicalContext: "This is the fourth consecutive session of a risk-on regime, the longest stretch since Q2.",
      affectedAssets: ["NASDAQ", "S&P 500"],
      tickers: ["NQ", "ES"],
    },
    {
      id: "n7",
      tag: "event",
      time: "3h ago",
      minutesAgo: 168,
      source: "WGC",
      category: "commodity",
      impact: "low",
      direction: "up",
      title: "Gold grinds higher on central bank buying",
      marketImpact: "Safe-haven demand ↑",
      confidence: 61,
      whatHappened: "Safe-haven demand and official-sector buying offset real-yield headwinds; gold prints $2,614.",
      whyItMatters: "A steadily bid gold price alongside risk-on equities is a mild signal that positioning is still hedged.",
      historicalContext: "Central bank gold buying has run above its 5-year average for six straight quarters.",
      affectedAssets: ["Gold", "Real yields"],
      tickers: ["GC", "XAU"],
    },
    {
      id: "n8",
      tag: "event",
      time: "4h ago",
      minutesAgo: 240,
      source: "BLS",
      category: "macro",
      impact: "medium",
      direction: "neutral",
      title: "Payrolls add 142k, unemployment steady",
      marketImpact: "Soft-landing narrative intact",
      confidence: 70,
      whatHappened: "Nonfarm payrolls add 142k; unemployment holds at 4.1%.",
      whyItMatters: "Labour market cooling gradually rather than breaking keeps the soft-landing case alive without forcing the Fed's hand.",
      historicalContext: "Payroll prints within 20k of consensus have historically produced muted, sub-0.3% index moves.",
      affectedAssets: ["Labor market", "Rates"],
      tickers: ["NFP"],
    },
    {
      id: "n9",
      tag: "event",
      time: "6h ago",
      minutesAgo: 360,
      source: "BEA",
      category: "macro",
      impact: "medium",
      direction: "up",
      title: "Q3 GDP revised up to 2.8%",
      marketImpact: "Growth backdrop supportive",
      confidence: 65,
      whatHappened: "Q3 GDP revised up to 2.8% annualized on resilient consumer spending.",
      whyItMatters: "Solid growth supports earnings but complicates the case for near-term rate cuts — a two-sided signal for equities.",
      historicalContext: "Upward GDP revisions this cycle have coincided with modest Fed hawkishness in the following meeting.",
      affectedAssets: ["GDP", "Consumer spending"],
      tickers: ["GDP"],
    },
    {
      id: "n10",
      tag: "alert",
      time: "9h ago",
      minutesAgo: 540,
      source: "Nikkei",
      category: "central-bank",
      impact: "low",
      direction: "neutral",
      title: "BoJ holds, watching yen weakness",
      marketImpact: "Equity vol ↑ (tail risk)",
      confidence: 58,
      whatHappened: "BoJ keeps policy unchanged; next hike unlikely before Q1 amid continued yen weakness.",
      whyItMatters: "Carry-trade unwind risk remains a tail risk for global equity volatility if yen weakness reverses sharply.",
      historicalContext: "The August carry-trade unwind followed a similar setup of prolonged BoJ inaction plus a weak yen.",
      affectedAssets: ["JPY", "Equity volatility"],
      tickers: ["JPY", "USDJPY"],
    },
    {
      id: "n11",
      tag: "event",
      time: "11h ago",
      minutesAgo: 660,
      source: "AP",
      category: "geopolitics",
      impact: "medium",
      direction: "up",
      title: "Red Sea shipping disruption lifts freight risk",
      marketImpact: "Inflation risk increases",
      confidence: 63,
      whatHappened: "Rerouting around the Cape lengthens supply chains, feeding into freight and commodity costs.",
      whyItMatters: "Longer supply chains are a second-round inflation risk that could complicate the disinflation narrative.",
      historicalContext: "Prior Red Sea disruptions added roughly 0.1-0.2pp to headline CPI with a 2-3 month lag.",
      affectedAssets: ["Energy", "Inflation"],
      tickers: ["CL", "CPI"],
    },
  ],
};
