begin;
drop policy if exists "Entitled users read own standing rules" on standing_rules;
drop policy if exists "Entitled users insert own standing rules" on standing_rules;
drop policy if exists "Entitled users update own standing rules" on standing_rules;
drop policy if exists "Entitled users delete own standing rules" on standing_rules;
create policy "Users manage own standing rules" on standing_rules for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Entitled users manage own trading goals" on trading_goals;
create policy "Users manage own trading goals" on trading_goals for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Entitled users manage own weekly reviews" on weekly_trade_reviews;
create policy "Users manage own weekly trade reviews" on weekly_trade_reviews for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users read retained trades" on trades;
drop policy if exists "Users insert own trades" on trades;
drop policy if exists "Users update own trades" on trades;
drop policy if exists "Users delete own trades" on trades;
create policy "Users manage own trades" on trades for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users read retained pre-market exercise" on pre_market_exercise;
drop policy if exists "Users insert own pre-market exercise" on pre_market_exercise;
drop policy if exists "Users update own pre-market exercise" on pre_market_exercise;
drop policy if exists "Users delete own pre-market exercise" on pre_market_exercise;
create policy "Users manage own pre-market exercise" on pre_market_exercise for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users read retained trade rule checks" on trade_rule_checks;
drop policy if exists "Users insert own trade rule checks" on trade_rule_checks;
drop policy if exists "Users update own trade rule checks" on trade_rule_checks;
drop policy if exists "Users delete own trade rule checks" on trade_rule_checks;
create policy "Users manage own trade rule checks" on trade_rule_checks for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users read retained analyses" on analyses;
drop policy if exists "Users insert own analyses" on analyses;
drop policy if exists "Users update own analyses" on analyses;
drop policy if exists "Users delete own analyses" on analyses;
create policy "Users manage own analyses" on analyses for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users read retained session reviews" on best_trade_of_day;
drop policy if exists "Users insert own session reviews" on best_trade_of_day;
drop policy if exists "Users update own session reviews" on best_trade_of_day;
drop policy if exists "Users delete own session reviews" on best_trade_of_day;
create policy "Users manage own best trade of day" on best_trade_of_day for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users insert within account limit" on funded_accounts;
drop policy if exists "Users delete own accounts" on funded_accounts;
drop policy if exists "Users update own accounts" on funded_accounts;
drop policy if exists "Users read own accounts" on funded_accounts;
create policy "Users manage own accounts" on funded_accounts for all using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop trigger if exists best_trade_entitlement_guard on best_trade_of_day;
drop function if exists enforce_best_trade_entitlement();
drop policy if exists "Entitled users upload own screenshots" on storage.objects;
create policy "Users upload own screenshots" on storage.objects for insert to authenticated with check (bucket_id = 'trade-screenshots' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "Entitled users read own screenshots" on storage.objects;
create policy "Users read own screenshots" on storage.objects for select to authenticated using (bucket_id = 'trade-screenshots' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop function if exists history_cutoff(uuid);
drop function if exists has_entitlement(text, uuid);
drop function if exists effective_entitlements(uuid);
-- Access rows/settings remain available for a later billing rollout.
commit;
