-- Superseded by avatars_private.sql.
--
-- This file created the avatars bucket as public, with a read policy of
-- `bucket_id = 'avatars'` and nothing else. Since a photo is stored at
-- {user_id}/avatar.{ext}, that made every profile photo readable by anyone
-- holding a user id. Run avatars_private.sql instead: it creates the same
-- bucket closed, and flips an existing one to private.
